// <auto-generated />
namespace VShuttle.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class newcolumnadded_userinfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newcolumnadded_userinfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201706271155375_newcolumnadded_userinfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
